apiVersion: v1
kind: Service
metadata:
  name: guestbook-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: guestbook-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
